services:
  - type: web
    name: nexus-backend
    env: python
    plan: free
    region: ohio
    rootDir: backend
    autoDeploy: true
    healthCheckPath: /api/health/
    buildCommand: bash ./build.sh
    startCommand: gunicorn django_core.config.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --timeout 60
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: DJANGO_SETTINGS_MODULE
        value: django_core.config.settings.prod
      - key: DEBUG
        value: "false"
      - key: SECRET_KEY
        value: 31a8d6d231ee2342d9db57e2b3511221
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: nexus-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: nexus-redis
          property: connectionString
      - key: CELERY_BROKER_URL
        fromService:
          type: redis
          name: nexus-redis
          property: connectionString
      - key: CELERY_RESULT_BACKEND
        fromService:
          type: redis
          name: nexus-redis
          property: connectionString
      - key: CORS_ALLOWED_ORIGINS
        value: https://nexus-b8zu.onrender.com,http://localhost:3000,http://localhost:5173
      - key: CSRF_TRUSTED_ORIGINS
        value: https://nexus-b8zu.onrender.com,https://nexus-backend-xsl2.onrender.com
      - key: CORS_ALLOW_ALL_ORIGINS
        value: "false"
      - key: CORS_ALLOW_CREDENTIALS
        value: "true"
      - key: ADMIN_EMAIL
        value: dankarish.dk@gmail.com
      - key: ADMIN_USERNAME
        value: dankarish
      - key: ADMIN_PASSWORD
        sync: false
      - key: ADMIN_RESET_PASSWORD_ON_START
        value: "false"
      - key: DERIV_API_KEY
        value: wElagIDHA2n3I4P
      - key: DERIV_APP_ID
        value: "113709"
      - key: DERIV_OAUTH_CALLBACK_URL
        value: https://nexus-b8zu.onrender.com/oauth/callback
      - key: ENVIRONMENT
        value: production

  - type: web
    name: nexus-frontend
    env: static
    rootDir: frontend
    autoDeploy: true
    buildCommand: npm ci && npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_BASE_URL
        value: https://nexus-backend-xsl2.onrender.com/api/v1
      - key: VITE_APP_ENV
        value: production
      - key: VITE_APP_NAME
        value: "Nexus Trading Bot"
      - key: VITE_DERIV_REDIRECT_URL
        value: https://nexus-b8zu.onrender.com/oauth/callback
      - key: VITE_WS_BASE_URL
        value: wss://nexus-backend-xsl2.onrender.com/ws

  - type: redis
    name: nexus-redis
    plan: free
    region: ohio
    ipAllowList:
      - source: 0.0.0.0/0

databases:
  - name: nexus-db
    databaseName: nexus_db_zay2
    plan: free
    region: ohio
