# Generated by Django 4.2.10 on 2026-02-09 22:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_deriv_account_type_user_deriv_country_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="deriv_access_token",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="deriv_accounts",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
