# Generated by Django 4.2.10 on 2026-02-19 15:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("USER_LOGIN", "User Login"),
                    ("USER_LOGOUT", "User Logout"),
                    ("TRADE_CREATED", "Trade Created"),
                    ("TRADE_CLOSED", "Trade Closed"),
                    ("WITHDRAWAL", "Withdrawal"),
                    ("DEPOSIT", "Deposit"),
                    ("COMMISSION_AWARDED", "Commission Awarded"),
                    ("SYSTEM_SETTINGS_UPDATED", "System Settings Updated"),
                ],
                max_length=32,
            ),
        ),
    ]
