# Generated by Django 4.2.10 on 2026-02-07 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deriv_account_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=128, null=True
                    ),
                ),
                (
                    "account_type",
                    models.CharField(
                        choices=[("DEMO", "Demo"), ("REAL", "Real")],
                        default="DEMO",
                        max_length=10,
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=8)),
                (
                    "balance",
                    models.DecimalField(decimal_places=6, default=0, max_digits=20),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("is_default", models.BooleanField(default=False)),
                (
                    "markup_percentage",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-is_default", "-created_at"),
            },
        ),
    ]
