# Generated by Django 4.2.10 on 2026-02-13 12:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="deriv_account_id",
        ),
        migrations.AddField(
            model_name="account",
            name="account_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Deriv login ID",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="bot_contract",
            field=models.CharField(default="RISE", max_length=10),
        ),
        migrations.AddField(
            model_name="account",
            name="bot_cooldown_seconds",
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name="account",
            name="bot_daily_loss_limit",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="bot_duration",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="bot_duration_unit",
            field=models.CharField(default="m", max_length=5),
        ),
        migrations.AddField(
            model_name="account",
            name="bot_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="account",
            name="bot_follow_signal",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="account",
            name="bot_max_trades_per_session",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="account",
            name="bot_min_confidence",
            field=models.FloatField(default=0.7),
        ),
        migrations.AddField(
            model_name="account",
            name="bot_stake",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="bot_strategy",
            field=models.CharField(default="scalping", max_length=50),
        ),
        migrations.AddField(
            model_name="account",
            name="bot_symbol",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="bot_trade_type",
            field=models.CharField(default="RISE_FALL", max_length=20),
        ),
        migrations.AddField(
            model_name="account",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("INACTIVE", "Inactive"),
                    ("DISABLED", "Disabled"),
                ],
                default="ACTIVE",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="account_type",
            field=models.CharField(
                choices=[("REAL", "Real"), ("DEMO", "Demo")],
                default="DEMO",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="currency",
            field=models.CharField(default="USD", max_length=10),
        ),
    ]
