# Generated by Django 4.2.10 on 2026-02-13 12:20

from django.db import migrations

def fill_account_id(apps, schema_editor):
    Account = apps.get_model("accounts", "Account")
    for a in Account.objects.filter(account_id__isnull=True):
        a.account_id = f"ACC-{a.id}"
        a.save(update_fields=["account_id"])
    for a in Account.objects.filter(account_id=""):
        a.account_id = f"ACC-{a.id}"
        a.save(update_fields=["account_id"])

class Migration(migrations.Migration):
    dependencies = [("accounts", "0002_remove_account_deriv_account_id_account_account_id_and_more")]
    operations = [migrations.RunPython(fill_account_id, migrations.RunPython.noop)]
