# Generated by Django 4.2.10 on 2026-02-13 12:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_backfill_account_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="account_id",
            field=models.CharField(
                db_index=True, help_text="Deriv login ID", max_length=50, unique=True
            ),
        ),
    ]
