# Generated by Django 4.2.10 on 2026-02-13 09:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trades", "0002_trade_type_and_contract"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trade",
            name="status",
            field=models.CharField(
                choices=[
                    ("OPEN", "Open"),
                    ("WON", "Won"),
                    ("LOST", "Lost"),
                    ("CLOSED", "Closed"),
                    ("CANCELLED", "Cancelled"),
                    ("FAILED", "Failed"),
                ],
                default="OPEN",
                max_length=16,
            ),
        ),
    ]
