# Generated by Django 4.2.10 on 2026-02-13 12:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trades", "0003_alter_trade_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="trade",
            name="signal_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=128, null=True
            ),
        ),
    ]
