# Generated by Django 4.2.10 on 2026-02-14 09:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trades", "0004_trade_signal_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trade",
            name="signal_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Signal ID that triggered this trade",
                max_length=128,
                null=True,
            ),
        ),
    ]
